language: node_js

node_js:
  - "8"
scripts
  - npm install codecov -g
after_success:
  - codecov

sudo: false

branches:
   only:
   - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn jest --runInBand --coverage